version: 1.0.{build}
skip_tags: true
build:
  publish_nuget: true
  verbosity: minimal
environment:
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
install:
  - choco install doxygen.portable
after_test:
  - ps: C:/ProgramData/chocolatey/lib/doxygen.portable/tools/doxygen.exe doxygen.config
  - ps: ./pushDocumentation.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:appveyor_repo_branch